name: BattleChestEvents
version: 0.1
author: Eegabooga

description: This plugin allows a player to create a chest that spawns at a set time with set loot.

main: net.thebattlecraft.eegabooga.BattleChestEvents.BattleChestEvents
commands:
    newchestevent:
        aliases: nce
        description: Set the chest event
        usage: /<command> <stuff> 
commands:
    cancelchestevent:
        aliases: cce
        description: Cancel the chest event
        usage: /<command>

#
#commands:
#   bce:
#      description: Base command for the BattleChestEvent plugin.
#      usage: |
#           /<command>
#